{% set name = "pylhc_submitter" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylhc_submitter-{{ version }}.tar.gz
  sha256: 7ccba499cbc717eb68501a79e8d90ae81fb4d5ac0db262d2be98667c797b60a9

build:
  number: 0
  skip: true  # [win]
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - numpy >=1.24
    - scipy >=1.10
    - pandas >=2.1
    - tfs-pandas >=3.8
    - matplotlib-base >=3.8
    - python-htcondor >=8.9.2
    - generic_parser >=1.1

test:
  imports:
    - pylhc_submitter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pylhc/submitter
  summary: Submitter for parametric studies to an HTCondor cluster.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A Python package to help parametrize and submit simulations to an HTCondor cluster.
  doc_url: https://pylhc.github.io/submitter/

extra:
  recipe-maintainers:
    - fsoubelet
