{% set name = "pylhc_submitter" %}
{% set version = "2.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylhc_submitter-{{ version }}.tar.gz
  sha256: b378f1dd9a0e00bc0c44fd5b971a6ecdd58a9296bda33dbb411922f247a0a902

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - scipy >=1.10
    - pandas >=2.1
    - tfs-pandas >=3.8
    - matplotlib-base >=3.8
    - python-htcondor >=8.9.2
    - generic_parser >=1.1

test:
  imports:
    - pylhc_submitter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pylhc/submitter
  summary: Submitter for parametric studies to an HTCondor cluster.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A Python package to help parametrize and submit simulations to an HTCondor cluster.
  doc_url: https://pylhc.github.io/submitter/

extra:
  recipe-maintainers:
    - fsoubelet
