{% set name = "pylhc_submitter" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylhc_submitter-{{ version }}.tar.gz
  sha256: 2ff6dffdfb1fa6604733d0f3f7262b319e0173435152de1aa29d47117fa7b501

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - generic_parser >=1.0.8
    - python-htcondor >=8.9.2  # [not win]
    - matplotlib-base >=3.2.0
    - numpy >=1.19
    - pandas >=1.0
    - python
    - scipy >=1.4.0
    - tfs-pandas >=2.0

test:
  imports:
    - pylhc_submitter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pylhc/submitter
  summary: Submitter for parametric studies to an HTCondor cluster.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A Python package to help parametrize and submit simulations to an HTCondor cluster.
  doc_url: https://pylhc.github.io/submitter/

extra:
  recipe-maintainers:
    - fsoubelet
